rails_test/testing/config/routes.rb
Rails.application.routes.draw do
  resources :zombies
  get 'pages/home'

  get 'pages/about'

  resources :users

   resources :articles do
       resources :comments
   end

  match ':controller(/:action(/:id))', :via => :get

  get '/welcome/:id', to: 'welcome#show'
  post 'welcome/:id', to: 'welcome#update'

  get '/form_test', to: 'welcome#form_test'

  get '/login', action: 'login', controller: 'session'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/signup_path', to: 'session#create'

  get '/signup', to: 'users#new'

end

rails_test/testing/app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    validates :title, presence:true, length: { maximum: 50 }
    validates :post, presence:true, length: { minimum: 3}
end

rails_test/testing/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :post, :user_id, :published_date)
    end
end

rails_test/testing/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails_test/testing/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_test/testing/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

rails_test/testing/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>User</th>
      <th>Published date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.post %></td>
        <td><%= article.user_id %></td>
        <td><%= article.published_date %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

rails_test/testing/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

rails_test/testing/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @article.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>


<h2>Comments</h2>
<% @article.comments.each do |c| %>
<p>
    <strong>Commenter:</strong>
    <%= c.commenter %>
</p>

<p>
    <strong>Comment:</strong>
    <%= c.body%>
</p>


<% end %>


<%= form_for([@article, @article.comments.build]) do |f| %>
<p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
</p>

<p>
    <%= f.label :comment %><br>
    <%= f.text_field :body %>
</p>

<%= f.submit %>
<% end %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>