rails_test/testing/config/routes.rb
Rails.application.routes.draw do
  resources :zombies
  get 'pages/home'

  get 'pages/about'

  resources :users

   resources :articles do
       resources :comments
   end

  match ':controller(/:action(/:id))', :via => :get

  get '/welcome/:id', to: 'welcome#show'
  post 'welcome/:id', to: 'welcome#update'

  get '/form_test', to: 'welcome#form_test'

  get '/login', action: 'login', controller: 'session'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/signup_path', to: 'session#create'

  get '/signup', to: 'users#new'

end

rails_test/testing/app/controllers/session_controller.rb
class SessionController < ApplicationController
    def index

    end

    def login
        render "auth/login"
    end

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])

        else
            flash.now[:danger] = "Invalid email/password combination."
            render 'new'
        end
    end

    def signup_path
        render 'new'
    end

    def destroy
    end
end

rails_test/testing/app/helpers/session_helper.rb
module SessionHelper
end

rails_test/testing/app/views/session/index.html.erb
<h1>Hello And Welcome</h1>

rails_test/testing/app/views/session/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>