rails_test/testing/config/routes.rb
Rails.application.routes.draw do
  resources :zombies
  get 'pages/home'

  get 'pages/about'

  resources :users

   resources :articles do
       resources :comments
   end

  match ':controller(/:action(/:id))', :via => :get

  get '/welcome/:id', to: 'welcome#show'
  post 'welcome/:id', to: 'welcome#update'

  get '/form_test', to: 'welcome#form_test'

  get '/login', action: 'login', controller: 'session'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/signup_path', to: 'session#create'

  get '/signup', to: 'users#new'

end

rails_test/testing/app/models/user.rb
require 'bcrypt'
require 'digest/sha1'

class User < ActiveRecord::Base
    include BCrypt

    has_many :articles
    attr_accessor :password

    before_save :encrypt_password
    after_save :clear_password

    # basic hash password
    # encrypted_password= Digest::SHA1.hexdigest(password)
    #this include salt to encrypt
    # salt= Digest::SHA1.hexdigest("# We add {email} as unique value and #{Time.now} as random value")
    # encrypted_password= Digest::SHA1.hexdigest("Adding #{salt} to {password}")

    #EMAIL_REGEX = /^[A_Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i   #this is error
    #EMAIL_REGEX = /A[w+-.]+@[a-zd-.]+.[a-z]+z/i

    #EMAIL_REGEX = ^.+@.+$
    EMAIL_REGEX =  /\A[A_Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z/i
    validates :password, confirmation: true, presence: true, uniqueness: true, length: { in: 8..30 }
    validates :email, presence: true, uniqueness: true, format: EMAIL_REGEX

    # check why you implement this 2 function href="https://github.com/codahale/bcrypt-ruby"
    # def password
    #     @password ||= Password.new(password_hash)
    # end

    # def password=(new_password)
    #     @password = Password.create(new_password)
    #     self.password_hash = @password
    # end

    def encrypt_password
        if password.present?
            self.salt =BCrypt::Engine.generate_salt
            self.encrypt_password = BCrypt::Engine.hash_secret(password, salt)
        end
    end

    def clear_password
        self.password = nil
    end
end

rails_test/testing/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:password, :email, :firstname, :lastname)
    end
end

rails_test/testing/app/helpers/users_helper.rb
module UsersHelper
end

rails_test/testing/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
      <p> Password Conformation:</p><br>
      <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
     <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_test/testing/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

rails_test/testing/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>Email</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

rails_test/testing/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

rails_test/testing/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>